### ISSUE TITLE
Support next branch of Capstone?

### ISSUE THREAD

**Issue by ZhangZhuoSJTU** [capstone-rust/capstone-sys#30] opened 2018-10-17 20:08 UTC
I am not sure whether this is necessary. But from my case, I am trying to get access info of registers. As [this post](https://www.capstone-engine.org/op_access.html) indicates, capstone in next branch has support `cs_regs_access()` which is much more useful than `reg_read` and `reg_write`.

Thus, what I did are as follows:

+ use [update_capstone.sh](https://github.com/capstone-rust/capstone-sys/blob/master/scripts/update_capstone.sh) to update capstone into the next branch.

+ Because in the new version of capstone, header files are moved into [include/capstone](https://github.com/aquynh/capstone/tree/master/include/capstone) (Actually, the newest commit of capstone's master branch has did that too), I edit build.rs like:

```rust
header_search_paths.push([CAPSTONE_DIR, "include", "capstone"].iter().collect());
```

+ `cargo build --features use_bindgen --all`

However, after that, I gather following warning.

```
... <similar warning>...
warning: capstone/arch/X86/X86Mapping.c:2811:31: warning: missing field 'access' initializer [-Wmissing-field-initializers]
warning:         { X86_ADD_FrST0, X86_REG_ST0 },
warning:                                      ^
warning: capstone/arch/X86/X86Mapping.c:2812:31: warning: missing field 'access' initializer [-Wmissing-field-initializers]
warning:         { X86_SUB_FrST0, X86_REG_ST0 },
warning:                                      ^
warning: capstone/arch/X86/X86Mapping.c:2813:32: warning: missing field 'access' initializer [-Wmissing-field-initializers]
warning:         { X86_SUBR_FrST0, X86_REG_ST0 },
warning:                                       ^
warning: capstone/arch/X86/X86Mapping.c:2814:31: warning: missing field 'access' initializer [-Wmissing-field-initializers]
warning:         { X86_MUL_FrST0, X86_REG_ST0 },
warning:                                      ^
warning: capstone/arch/X86/X86Mapping.c:2815:31: warning: missing field 'access' initializer [-Wmissing-field-initializers]
warning:         { X86_DIV_FrST0, X86_REG_ST0 },
warning:                                      ^
warning: capstone/arch/X86/X86Mapping.c:2816:32: warning: missing field 'access' initializer [-Wmissing-field-initializers]
warning:         { X86_DIVR_FrST0, X86_REG_ST0 },
warning:                                       ^
warning: 102 warnings generated.
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: file: /private/tmp/capstone-sys/target/debug/build/capstone-sys-70045b853a024ad6/out/libcapstone.a(M68KModule.o) has
no symbols
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: file: /private/tmp/capstone-sys/target/debug/build/capstone-sys-70045b853a024ad6/out/libcapstone.a(M680XModule.o) has no symbols
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: file: /private/tmp/capstone-sys/target/debug/build/capstone-sys-70045b853a024ad6/out/libcapstone.a(M680XInstPrinter.o) has no symbols
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: file: /private/tmp/capstone-sys/target/debug/build/capstone-sys-70045b853a024ad6/out/libcapstone.a(M680XDisassembler.o) has no symbols
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: file: /private/tmp/capstone-sys/target/debug/build/capstone-sys-70045b853a024ad6/out/libcapstone.a(TMS320C64xInstPrinter.o) has no symbols
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: file: /private/tmp/capstone-sys/target/debug/build/capstone-sys-70045b853a024ad6/out/libcapstone.a(TMS320C64xDisassembler.o) has no symbols
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: file: /private/tmp/capstone-sys/target/debug/build/capstone-sys-70045b853a024ad6/out/libcapstone.a(TMS320C64xModule.o) has no symbols
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: file: /private/tmp/capstone-sys/target/debug/build/capstone-sys-70045b853a024ad6/out/libcapstone.a(TMS320C64xMapping.o) has no symbols
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: file: /private/tmp/capstone-sys/target/debug/build/capstone-sys-70045b853a024ad6/out/libcapstone.a(EVMModule.o) has no symbols
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: file: /private/tmp/capstone-sys/target/debug/build/capstone-sys-70045b853a024ad6/out/libcapstone.a(EVMMapping.o) has
no symbols
    Finished dev [unoptimized + debuginfo] target(s) in 0.97s
```

I thought it was caused by the wrong way of compiling capstone. But I am not so familiar with capstone's source files. So that I am wondering whether anyone could help me. I will also work on this but it might cause more time.

Thanks a lot.

**Comment by tmfink** [comment] 2018-10-17 23:25
This is a duplicate of #29; moving discussion there

**Closed as completed by tmfink** 2018-10-17 23:25 UTC
